export const ERROR_CODES = {
  LISTING_NOT_FOUND: "LISTING_NOT_FOUND",
  INVALID_QUERY: "INVALID_QUERY",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  LIMIT_REACHED: "LIMIT_REACHED",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
